# Generated by Django 4.2.14 on 2024-08-16 18:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('assets_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetListing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.CharField(max_length=255)),
                ('asset_type', models.CharField(max_length=255)),
                ('classification', models.CharField(max_length=255)),
                ('classification_value', models.FloatField()),
                ('asset_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets_management.assetvaluemapping')),
                ('owner_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets_management.department')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
