# Generated by Django 4.2.14 on 2024-08-25 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets_management', '0006_assetlisting_availability_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetlisting',
            name='dt_predicted_risk_level',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assetlisting',
            name='ensemble_predicted_risk_level',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assetlisting',
            name='rf_predicted_risk_level',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
