# Generated by Django 4.2.14 on 2024-08-25 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets_management', '0007_assetlisting_dt_predicted_risk_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetlisting',
            name='dt_predicted_risk_level',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='assetlisting',
            name='ensemble_predicted_risk_level',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='assetlisting',
            name='rf_predicted_risk_level',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
