# Generated by Django 4.2.14 on 2024-08-25 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets_management', '0008_alter_assetlisting_dt_predicted_risk_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetlisting',
            name='risk_treatment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
