# Generated by Django 4.2.14 on 2024-09-17 19:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('assets_management', '0009_assetlisting_risk_treatment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassificationReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model_name', models.CharField(max_length=255)),
                ('precision', models.FloatField()),
                ('recall', models.FloatField()),
                ('f1_score', models.FloatField()),
                ('support', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConfusionMatrix',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model_name', models.CharField(max_length=255)),
                ('true_label', models.CharField(max_length=255)),
                ('predicted_label', models.CharField(max_length=255)),
                ('count', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
