from django.core.management.base import BaseCommand
from assets_management.models import Asset

class Command(BaseCommand):
    def handle(self, *args, **options):
        assets = [
            # Batch 1: 100 Unique Cloud Assets
            ('Cloud Storage Solutions', 'Services that provide scalable storage over the internet.'),
            ('Cloud Computing Platforms', 'Services that offer computing power, storage, and other resources via the cloud.'),
            ('SaaS Applications', 'Software applications hosted by a provider and accessed via the internet.'),
            ('Cloud Backup Solutions', 'Services that provide data backup over the cloud.'),
            ('Cloud Security Services', 'Services that provide security for cloud-based applications and data.'),
            ('Virtual Machines', 'Software-based emulations of physical computers running in the cloud.'),
            ('Cloud-Based Development Environments', 'Tools and platforms for developing applications hosted in the cloud.'),
            ('API Management Platforms', 'Tools for managing application programming interfaces (APIs) in the cloud.'),
            ('Content Delivery Networks (CDN)', 'Distributed servers that deliver web content based on the user’s geographic location.'),
            ('Cloud Load Balancers', 'Tools that distribute network or application traffic across multiple servers.'),
            ('Cloud Monitoring Services', 'Tools for tracking performance and availability of cloud services.'),
            ('Cloud Cost Management Tools', 'Services that help manage and optimize cloud spending.'),
            ('Web Hosting Services', 'Platforms for hosting websites and web applications in the cloud.'),
            ('Cloud Networking Services', 'Services that facilitate networking in the cloud environment.'),
            ('Disaster Recovery as a Service (DRaaS)', 'Cloud computing service that protects applications and data from disruption.'),
            ('Cloud Database Services', 'Managed database services in the cloud.'),
            ('Cloud-Based Machine Learning Services', 'Platforms for developing and deploying machine learning models in the cloud.'),
            ('Blockchain as a Service (BaaS)', 'Cloud-based service that allows users to build, host, and use blockchain apps.'),
            ('IoT Platforms', 'Cloud services that enable connectivity and management of Internet of Things devices.'),
            ('Web Application Firewalls', 'Security services that monitor and filter HTTP traffic to and from a web application.'),
            ('Identity and Access Management (IAM)', 'Services that manage user identities and access privileges in the cloud.'),
            ('Email Services', 'Cloud-based platforms for managing email communications.'),
            ('Collaboration Tools', 'Applications that facilitate team collaboration and communication in the cloud.'),
            ('Online Backup Services', 'Services that provide secure cloud storage for data backups.'),
            ('Virtual Private Cloud (VPC)', 'Private cloud infrastructure hosted within a public cloud environment.'),
            ('Remote Desktop Services', 'Tools that allow users to access desktop environments hosted in the cloud.'),
            ('Serverless Computing', 'Cloud computing model that runs code in response to events without managing servers.'),
            ('Cloud Workflow Automation', 'Tools for automating business processes and workflows in the cloud.'),
            ('E-commerce Platforms', 'Cloud-based solutions for building and managing online stores.'),
            ('Cloud-Based CRM Solutions', 'Customer Relationship Management systems hosted in the cloud.'),
            ('Online Learning Platforms', 'Cloud-based services for delivering e-learning content.'),
            ('Telephony Services', 'Cloud-based communication services, including VoIP.'),
            ('Video Conferencing Tools', 'Cloud solutions for virtual meetings and webinars.'),
            ('Digital Asset Management Systems', 'Cloud-based systems for organizing, storing, and sharing digital assets.'),
            ('Marketing Automation Tools', 'Cloud applications for automating marketing tasks and campaigns.'),
            ('Customer Support Software', 'Cloud-based platforms for managing customer support interactions.'),
            ('Event Management Software', 'Cloud solutions for planning and managing events.'),
            ('Project Management Tools', 'Cloud applications for tracking project progress and collaboration.'),
            ('Human Resources Management Systems', 'Cloud-based HR solutions for managing employee data.'),
            ('Accounting Software', 'Cloud solutions for managing financial transactions and reporting.'),
            ('Inventory Management Systems', 'Cloud applications for managing inventory and supply chains.'),
            ('Content Management Systems', 'Platforms for managing digital content and publications.'),
            ('Business Intelligence Tools', 'Cloud-based analytics tools for business data insights.'),
            ('Survey Tools', 'Cloud applications for creating and distributing surveys.'),
            ('Online Payment Processing Services', 'Cloud-based platforms for managing online transactions.'),
            ('Social Media Management Tools', 'Cloud solutions for managing social media accounts and campaigns.'),
            ('API Testing Tools', 'Services for testing application programming interfaces in the cloud.'),
            ('Remote Monitoring Solutions', 'Cloud applications for monitoring assets and operations remotely.'),
            ('Machine Learning Platforms', 'Cloud services for building and deploying machine learning models.'),
            ('Data Warehousing Solutions', 'Cloud-based data storage and analysis platforms.'),
            ('User Experience Testing Tools', 'Cloud applications for conducting user experience research.'),
            ('Video Hosting Services', 'Platforms for storing and sharing video content online.'),
            ('Online Form Builders', 'Cloud applications for creating and managing web forms.'),
            ('Freemium SaaS Platforms', 'SaaS applications offering free and paid tiers of service.'),
            ('Cloud-Based IDEs', 'Integrated Development Environments hosted in the cloud.'),
            ('Podcast Hosting Services', 'Cloud platforms for hosting and distributing podcasts.'),
            ('Augmented Reality Services', 'Cloud solutions for developing and delivering augmented reality experiences.'),
            ('Virtual Event Platforms', 'Services for hosting virtual events and conferences.'),
            ('Online Reputation Management Tools', 'Cloud applications for monitoring and managing brand reputation.'),
            ('Digital Marketing Platforms', 'Cloud solutions for managing digital marketing campaigns.'),
            ('Peer-to-Peer Payment Services', 'Cloud-based platforms for facilitating direct payments between users.'),
            ('Remote IT Support Services', 'Cloud-based support for managing IT issues remotely.'),
            ('Public Cloud Services', 'Services offered by third-party providers over the public internet.'),
            ('Private Cloud Services', 'Cloud infrastructure dedicated to a single organization.'),
            ('Hybrid Cloud Solutions', 'Combining public and private cloud infrastructures.'),
            ('Cloud Orchestration Tools', 'Services that automate the management of complex cloud environments.'),
            ('Test Automation Tools', 'Cloud services for automating software testing.'),
            ('Data Migration Services', 'Cloud solutions for migrating data between platforms.'),
            ('Application Performance Monitoring Tools', 'Services that monitor the performance of applications in the cloud.'),
            ('User Feedback Tools', 'Cloud applications for collecting user feedback and insights.'),
            ('Crowdsourcing Platforms', 'Cloud solutions for gathering ideas or services from a large group of people.'),
            ('APM Tools', 'Application Performance Management tools that monitor application health.'),
            ('Disaster Recovery Solutions', 'Services to ensure business continuity in case of disasters.'),
            ('E-signature Platforms', 'Cloud applications for electronic signatures and approvals.'),
            ('Video Editing Software', 'Cloud-based tools for editing video content.'),
            ('Design Tools', 'Cloud applications for graphic design and multimedia content creation.'),
            ('Stock Photo Libraries', 'Cloud platforms for sourcing stock images and media.'),
            ('Branding Tools', 'Cloud solutions for managing branding and marketing assets.'),
            ('Cloud Analytics Services', 'Services that provide analytics capabilities over cloud data.'),
            ('Compliance Management Software', 'Tools for managing regulatory compliance in the cloud.'),
            ('Workflow Management Tools', 'Cloud applications for optimizing and managing workflows.'),
            ('Multi-Cloud Management Solutions', 'Tools for managing services across multiple cloud providers.'),
            ('Server Monitoring Tools', 'Cloud services for monitoring server performance and health.'),
            ('Chatbot Platforms', 'Cloud solutions for developing and deploying chatbots.'),
            ('Personal Finance Management Tools', 'Cloud applications for managing personal finances.'),
            ('Web Application Development Frameworks', 'Frameworks for building web applications in the cloud.'),
            ('Business Continuity Software', 'Cloud solutions for ensuring operational resilience.'),
            ('Cloud-Based Time Tracking Tools', 'Applications for tracking time and productivity in the cloud.'),
            ('Performance Review Tools', 'Cloud solutions for managing employee performance reviews.'),
            ('Gamification Platforms', 'Cloud services for adding gamification elements to applications.'),
            ('Data Visualization Tools', 'Cloud applications for creating visual representations of data.'),
            ('Content Distribution Platforms', 'Cloud services for distributing digital content to various channels.'),
            ('Cloud Storage Gateway', 'A device or service that provides connectivity to cloud storage.'),
            ('Zero Trust Security Solutions', 'Cloud security solutions based on the zero trust model.'),

            # Batch 2: Another 100 Unique Cloud Assets
            ('Hybrid Cloud Management Tools', 'Solutions for managing hybrid cloud environments.'),
            ('API Gateways', 'Services that provide a single entry point for APIs.'),
            ('Machine Learning APIs', 'APIs that provide machine learning capabilities as a service.'),
            ('Cloud-Based SEO Tools', 'Applications for optimizing websites for search engines in the cloud.'),
            ('Web App Builders', 'Platforms for building web applications with minimal coding.'),
            ('Remote Learning Platforms', 'Cloud-based tools for delivering education remotely.'),
            ('Social Media Analytics Tools', 'Cloud applications for analyzing social media performance.'),
            ('Influencer Marketing Platforms', 'Services for connecting brands with influencers.'),
            ('SEO Management Tools', 'Cloud applications for managing search engine optimization efforts.'),
            ('Performance Optimization Tools', 'Services that improve the performance of web applications.'),
            ('Cloud-Based Business Process Management', 'Solutions for managing business processes in the cloud.'),
            ('Corporate Training Platforms', 'Cloud solutions for delivering employee training.'),
            ('Payment Gateways', 'Services that facilitate online payment processing.'),
            ('User Onboarding Tools', 'Cloud applications for onboarding users effectively.'),
            ('Social Media Advertising Tools', 'Cloud solutions for managing social media ad campaigns.'),
            ('API Monitoring Services', 'Tools for monitoring the health of APIs.'),
            ('Application Security Testing Tools', 'Services that assess application security in the cloud.'),
            ('User Authentication Services', 'Cloud solutions for managing user authentication and identity.'),
            ('Event Ticketing Platforms', 'Cloud-based solutions for managing ticket sales for events.'),
            ('E-commerce Checkout Solutions', 'Services that facilitate online transaction processing.'),
            ('Website Performance Monitoring Tools', 'Cloud applications for monitoring website performance.'),
            ('Digital Experience Platforms', 'Cloud solutions for managing digital customer experiences.'),
            ('Sustainability Management Software', 'Tools for managing corporate sustainability initiatives.'),
            ('Online Event Ticketing Systems', 'Cloud-based solutions for selling tickets to events.'),
            ('Virtual Reality Platforms', 'Cloud solutions for developing virtual reality experiences.'),
            ('Cloud Risk Management Tools', 'Applications for assessing and managing risks in the cloud.'),
            ('Subscription Management Software', 'Cloud applications for managing subscription billing.'),
            ('BIM Collaboration Tools', 'Cloud solutions for managing Building Information Modeling collaboration.'),
            ('Risk Assessment Tools', 'Cloud applications for assessing risks in projects.'),
            ('Collaboration and Communication Platforms', 'Services that enhance team communication.'),
            ('Supply Chain Management Software', 'Cloud solutions for managing supply chain processes.'),
            ('Order Management Systems', 'Cloud applications for managing orders and fulfillment.'),
            ('Telemedicine Platforms', 'Cloud solutions for delivering healthcare remotely.'),
            ('Online Scheduling Tools', 'Cloud applications for managing appointments and schedules.'),
            ('Cloud-Based HR Tools', 'Applications for managing human resources in the cloud.'),
            ('Digital Signage Solutions', 'Cloud services for managing digital signage displays.'),
            ('Cloud Compliance Solutions', 'Services for ensuring compliance in cloud environments.'),
            ('Sales Forecasting Tools', 'Cloud applications for predicting sales performance.'),
            ('Customer Experience Management Tools', 'Cloud solutions for managing customer experiences.'),
            ('Webinar Hosting Platforms', 'Cloud services for hosting online seminars.'),
            ('Digital Workflow Automation', 'Tools for automating workflows digitally.'),
            ('Cloud-Based Testing Services', 'Services for testing applications in the cloud.'),
            ('Employee Engagement Platforms', 'Cloud solutions for measuring and improving employee engagement.'),
            ('Online Payment Solutions', 'Cloud applications for processing payments online.'),
            ('Healthcare Management Systems', 'Cloud solutions for managing healthcare facilities and services.'),
            ('Real Estate Management Software', 'Cloud applications for managing real estate properties.'),
            ('Shipping and Fulfillment Solutions', 'Cloud-based services for managing shipping and fulfillment.'),
            ('Social Listening Tools', 'Cloud applications for monitoring social media conversations.'),
            ('Sales Enablement Tools', 'Cloud solutions for providing resources to sales teams.'),
            ('Talent Acquisition Platforms', 'Cloud applications for recruiting and hiring talent.'),
            ('Knowledge Management Systems', 'Cloud solutions for managing organizational knowledge.'),
            ('Regulatory Compliance Software', 'Tools for managing compliance with regulations.'),
            ('Legal Management Software', 'Cloud solutions for managing legal processes and documents.'),
            ('Procurement Management Systems', 'Cloud applications for managing procurement processes.'),
            ('Facility Management Software', 'Cloud solutions for managing facilities and maintenance.'),
            ('Corporate Event Management Software', 'Tools for managing corporate events and meetings.'),
            ('HR Analytics Tools', 'Cloud applications for analyzing human resources data.'),
            ('Cloud-Based Gaming Services', 'Platforms for hosting and managing online games.'),
            ('Online Recipe Management Tools', 'Cloud solutions for managing recipes and cooking instructions.'),
            ('Cloud Document Management Systems', 'Services for managing documents in the cloud.'),
            ('IoT Device Management Platforms', 'Cloud solutions for managing Internet of Things devices.'),
            ('Subscription Box Services', 'Cloud applications for managing subscription box businesses.'),
            ('Online Community Platforms', 'Cloud solutions for building and managing online communities.'),
            ('Virtual Assistant Services', 'Cloud applications for providing virtual assistant support.'),
            ('Gamification in Education Tools', 'Cloud solutions for applying gamification in educational contexts.'),
            ('Online Payment Gateways', 'Cloud applications for facilitating online payments.'),
            ('Website Builders', 'Cloud platforms for creating and managing websites.'),
            ('Online Learning Management Systems', 'Cloud solutions for delivering online courses and training.'),
            ('Business Process Automation Tools', 'Services that automate business processes.'),
            ('Employee Training Platforms', 'Cloud applications for providing employee training.'),
            ('Content Curation Tools', 'Cloud solutions for aggregating and managing digital content.'),
            ('Cloud-Based Scheduling Software', 'Applications for scheduling appointments and meetings.'),
            ('Energy Management Software', 'Cloud solutions for managing energy consumption and efficiency.'),
            ('Customer Loyalty Programs', 'Cloud applications for managing customer loyalty initiatives.'),
            ('HR Management Software', 'Cloud solutions for managing human resources processes.'),
            ('Health and Safety Management Systems', 'Cloud applications for managing workplace health and safety.'),
            ('Corporate Social Responsibility Software', 'Cloud solutions for managing CSR initiatives.'),
            ('Property Management Software', 'Cloud applications for managing rental properties.'),
            ('Fleet Management Solutions', 'Cloud services for managing vehicle fleets.'),
            ('Digital Asset Protection Tools', 'Cloud applications for securing digital assets.'),
            ('Online Inventory Management Systems', 'Cloud solutions for managing inventory levels and sales.'),
            ('Automated Customer Feedback Tools', 'Cloud applications for gathering customer feedback automatically.'),
            ('Cloud-Based Performance Management Tools', 'Applications for managing performance in organizations.'),
            ('Online Appointment Scheduling Software', 'Cloud solutions for scheduling appointments.'),
            ('Crowdfunding Platforms', 'Cloud services for raising funds through collective contributions.'),
            ('Remote IT Management Tools', 'Cloud applications for managing IT resources remotely.'),
            ('Digital Marketing Analytics Tools', 'Cloud solutions for analyzing marketing campaign effectiveness.'),
            ('Employee Scheduling Software', 'Cloud applications for scheduling employee shifts.'),
            ('Business Intelligence and Analytics Platforms', 'Cloud solutions for business data analysis.'),
            ('Online Fundraising Platforms', 'Cloud services for raising funds online.'),
            ('Digital Publishing Tools', 'Cloud applications for managing digital publications.'),
            ('Online Travel Booking Systems', 'Cloud solutions for managing travel bookings and itineraries.'),
            ('E-learning Platforms', 'Cloud services for delivering education online.'),
            ('Web Hosting Control Panels', 'Cloud applications for managing web hosting accounts.'),
            ('Event Planning Software', 'Cloud solutions for managing event logistics.'),
            ('Online Course Creation Tools', 'Cloud applications for creating and selling online courses.'),
            ('Survey and Polling Tools', 'Cloud services for conducting surveys and polls.'),
            ('Influencer Collaboration Platforms', 'Cloud solutions for managing influencer partnerships.'),
            ('Online Shopping Carts', 'Cloud applications for managing online retail transactions.'),
            ('Virtual Reality Training Solutions', 'Cloud services for delivering training in virtual environments.'),
            # AWS Services - Compute
            ('AWS EC2', 'Scalable virtual machine instances on Amazon Web Services (AWS).'),
            ('AWS Lambda', 'Serverless compute service for running code without provisioning servers.'),
            ('AWS Lightsail', 'Simplified virtual private server (VPS) service.'),
            ('AWS Fargate', 'Serverless compute engine for containers.'),
            ('AWS Batch', 'Batch processing jobs on AWS at any scale.'),
            ('AWS Elastic Beanstalk', 'Platform as a service for deploying and managing web applications.'),
            ('AWS Outposts', 'Fully managed AWS infrastructure and services on-premises.'),
            ('AWS App Runner', 'Service for deploying containerized web applications.'),
            ('AWS Wavelength', 'Extends AWS services to the edge of 5G networks.'),

            # AWS Services - Storage
            ('AWS S3', 'Scalable object storage service.'),
            ('AWS Glacier', 'Low-cost storage for archiving and long-term backups.'),
            ('AWS EFS', 'Elastic file storage for cloud services.'),
            ('AWS Storage Gateway', 'Hybrid cloud storage service for on-premises applications.'),
            ('AWS Backup', 'Centralized backup service for AWS resources.'),
            ('AWS FSx', 'Managed file systems for Windows and Lustre workloads.'),
            ('AWS S3 Glacier Deep Archive', 'Lowest-cost storage for data archiving.'),
            ('AWS Snowball', 'Data transfer device for large-scale data migration.'),
            ('AWS DataSync', 'Service for automating data transfer between on-premises storage and AWS.'),

            # AWS Services - Databases
            ('AWS RDS', 'Managed relational database service for MySQL, PostgreSQL, SQL Server, and Oracle.'),
            ('AWS DynamoDB', 'Managed NoSQL database service for key-value and document data models.'),
            ('AWS Redshift', 'Data warehouse for analyzing large datasets.'),
            ('AWS ElastiCache', 'Managed Redis and Memcached services for low-latency caching.'),
            ('AWS Neptune', 'Graph database service.'),
            ('AWS Aurora', 'Relational database engine built for the cloud, compatible with MySQL and PostgreSQL.'),
            ('AWS DocumentDB', 'Managed document database service compatible with MongoDB.'),
            ('AWS Timestream', 'Managed time series database for IoT and operational applications.'),
            ('AWS Keyspaces', 'Managed Apache Cassandra-compatible database service.'),
            ('AWS Quantum Ledger Database (QLDB)', 'Managed ledger database for cryptographically verifiable transactions.'),

            # AWS Services - Networking
            ('AWS CloudFront', 'Content delivery network (CDN) for fast distribution of content globally.'),
            ('AWS VPC', 'Virtual private cloud for networking AWS resources.'),
            ('AWS Route 53', 'Scalable Domain Name System (DNS) web service.'),
            ('AWS Direct Connect', 'Dedicated network connection from premises to AWS.'),
            ('AWS Elastic Load Balancing', 'Automatically distributes incoming traffic across multiple targets.'),
            ('AWS Transit Gateway', 'Connects VPCs and on-premises networks through a central hub.'),
            ('AWS Global Accelerator', 'Service for improving availability and performance of applications with users globally.'),
            ('AWS PrivateLink', 'Service for securely accessing services hosted on AWS without using public IPs.'),
            ('AWS App Mesh', 'Service mesh to manage communication between microservices.'),
            ('AWS VPN', 'Service for creating secure connections between AWS and on-premises networks.'),

            # AWS Services - Machine Learning & AI
            ('AWS SageMaker', 'Fully managed service for building, training, and deploying machine learning models.'),
            ('AWS Rekognition', 'Image and video analysis service.'),
            ('AWS Comprehend', 'Natural language processing service that uses machine learning to find insights.'),
            ('AWS Lex', 'Service for building conversational interfaces into applications.'),
            ('AWS Polly', 'Service for turning text into lifelike speech.'),
            ('AWS Forecast', 'Service for predicting future trends using machine learning.'),
            ('AWS Personalize', 'Service for building personalized recommendations.'),
            ('AWS Textract', 'Service for extracting text and data from documents.'),
            ('AWS Fraud Detector', 'Service for identifying potentially fraudulent activity using machine learning.'),
            ('AWS DeepLens', 'Deep learning-enabled video camera for computer vision applications.'),

            # AWS Services - Security
            ('AWS IAM', 'Identity and access management for AWS services.'),
            ('AWS Shield', 'Managed DDoS protection for AWS resources.'),
            ('AWS WAF', 'Web application firewall for protecting applications.'),
            ('AWS KMS', 'Managed encryption service for data protection.'),
            ('AWS Macie', 'Data security service that uses machine learning to automatically discover, classify, and protect sensitive data in AWS.'),
            ('AWS GuardDuty', 'Threat detection service that continuously monitors for malicious activity.'),
            ('AWS Secrets Manager', 'Service for managing and retrieving secrets, like API keys.'),
            ('AWS Certificate Manager', 'Service for managing SSL/TLS certificates.'),
            ('AWS Config', 'Service for assessing, auditing, and evaluating configurations of AWS resources.'),
            ('AWS Security Hub', 'Centralized security and compliance management service.'),

            # AWS Services - Developer Tools
            ('AWS CodeBuild', 'Fully managed continuous integration service.'),
            ('AWS CodeDeploy', 'Service for automating deployments.'),
            ('AWS CodePipeline', 'Service for continuous delivery.'),
            ('AWS CloudFormation', 'Service for defining and deploying infrastructure as code.'),
            ('AWS Cloud9', 'Cloud-based integrated development environment (IDE) for writing, running, and debugging code.'),
            ('AWS X-Ray', 'Service for debugging and analyzing distributed applications.'),
            ('AWS CodeArtifact', 'Managed artifact repository service for storing and sharing software packages.'),
            ('AWS CodeGuru', 'Machine learning service for automated code reviews and recommendations.'),
            ('AWS Device Farm', 'Service for testing mobile apps on real devices in the cloud.'),
            ('AWS AppConfig', 'Service for configuring and managing application settings in the cloud.'),

            # Azure Services - Compute
            ('Azure Virtual Machines', 'Scalable virtual machines on Microsoft Azure.'),
            ('Azure App Service', 'Platform as a service for hosting web applications, RESTful APIs, and mobile backends.'),
            ('Azure Kubernetes Service (AKS)', 'Managed Kubernetes service on Azure.'),
            ('Azure Functions', 'Serverless compute service on Azure.'),
            ('Azure Batch', 'Service for running large-scale parallel and high-performance computing jobs.'),
            ('Azure Virtual Machine Scale Sets', 'Service for managing a set of identical VMs.'),
            ('Azure Spring Cloud', 'Fully managed service for Spring Boot applications.'),
            ('Azure Container Instances', 'Managed service for running containers without orchestration.'),
            ('Azure Service Fabric', 'Platform for building microservices and container-based applications.'),
            ('Azure API Management', 'Service for creating, publishing, and managing APIs.'),
            
            # Azure Services - Storage
            ('Azure Blob Storage', 'Object storage for unstructured data.'),
            ('Azure File Storage', 'Managed file shares in the cloud.'),
            ('Azure Disk Storage', 'Persistent, highly durable storage for VMs.'),
            ('Azure Archive Storage', 'Low-cost storage for long-term retention of data.'),
            ('Azure Data Lake Storage', 'Scalable and secure data lake for high-performance analytics workloads.'),
            ('Azure Queue Storage', 'Managed message queuing service for asynchronous communication.'),
            ('Azure Table Storage', 'NoSQL key-value store for rapid development.'),
            ('Azure NetApp Files', 'Enterprise-class file storage service for Azure.'),
            ('Azure Blob Storage Gen2', 'Advanced hierarchical namespace for Blob storage.'),
            ('Azure File Sync', 'Service for synchronizing file servers with Azure Files.'),

            # Azure Services - Databases
            ('Azure SQL Database', 'Managed relational SQL database service on Azure.'),
            ('Azure Cosmos DB', 'Globally distributed, multi-model database service.'),
            ('Azure Database for MySQL', 'Managed MySQL database service on Azure.'),
            ('Azure Database for PostgreSQL', 'Managed PostgreSQL database service on Azure.'),
            ('Azure Database for MariaDB', 'Managed MariaDB database service on Azure.'),
            ('Azure SQL Managed Instance', 'Managed instance of SQL Server for Azure.'),
            ('Azure Synapse Analytics', 'Integrated analytics service for data integration and analytics.'),
            ('Azure Cache for Redis', 'Managed Redis caching service.'),
            ('Azure Data Explorer', 'Analytics service for big data queries.'),
            ('Azure SQL Data Warehouse', 'Managed data warehouse service on Azure.'),

            # Azure Services - Networking
            ('Azure Virtual Network', 'Service for securely connecting Azure resources.'),
            ('Azure Load Balancer', 'Service for distributing inbound traffic across multiple services.'),
            ('Azure Application Gateway', 'Web traffic load balancer that enables routing traffic based on URL.'),
            ('Azure ExpressRoute', 'Private connection from on-premises networks to Azure.'),
            ('Azure Traffic Manager', 'Service for routing traffic across multiple regions.'),
            ('Azure DNS', 'Hosting service for DNS domains.'),
            ('Azure VPN Gateway', 'Service for establishing secure connections to Azure from on-premises networks.'),
            ('Azure Firewall', 'Managed cloud-based network security service.'),
            ('Azure Bastion', 'Service for accessing virtual machines without exposing them to the public internet.'),
            ('Azure Front Door', 'Global, scalable entry point for web applications.'),
            
            # Azure Services - Machine Learning & AI
            ('Azure Machine Learning', 'Service for building, training, and deploying machine learning models.'),
            ('Azure Cognitive Services', 'APIs for adding AI capabilities like vision, speech, and language.'),
            ('Azure Bot Services', 'Service for building intelligent chatbots.'),
            ('Azure Databricks', 'Collaborative Apache Spark-based analytics service.'),
            ('Azure HDInsight', 'Fully-managed cloud service for big data analytics using open-source frameworks.'),
            ('Azure Form Recognizer', 'AI service for extracting information from forms and documents.'),
            ('Azure Anomaly Detector', 'Service for detecting anomalies in time series data.'),
            ('Azure Personalizer', 'Service for creating personalized experiences.'),
            ('Azure Text Analytics', 'API for natural language processing.'),
            ('Azure Video Indexer', 'Service for extracting insights from videos.'),
            
            # Azure Services - Security
            ('Azure Active Directory', 'Identity and access management service.'),
            ('Azure Security Center', 'Unified security management and threat protection service.'),
            ('Azure Key Vault', 'Service for managing cryptographic keys and secrets.'),
            ('Azure DDoS Protection', 'Service for protecting applications from DDoS attacks.'),
            ('Azure Sentinel', 'Cloud-native security information and event management (SIEM) service.'),
            ('Azure Information Protection', 'Service for protecting sensitive information.'),
            ('Azure Policy', 'Service for enforcing organizational policies on resources.'),
            ('Azure Advanced Threat Protection', 'Service for identifying and investigating advanced threats.'),
            ('Azure Compliance Manager', 'Service for managing compliance with regulatory requirements.'),
            ('Azure Security Center', 'Service for monitoring security across Azure resources.'),

            # Azure Services - Developer Tools
            ('Azure DevOps', 'Comprehensive set of tools for software development.'),
            ('Azure Repos', 'Git repositories for source control.'),
            ('Azure Pipelines', 'Continuous integration and delivery service.'),
            ('Azure Artifacts', 'Managed package repository service.'),
            ('Azure Monitor', 'Service for collecting, analyzing, and acting on telemetry data.'),
            ('Azure Application Insights', 'Service for monitoring performance and usage of applications.'),
            ('Azure Functions', 'Event-driven serverless compute service.'),
            ('Azure Logic Apps', 'Service for automating workflows and integrating applications.'),
            ('Azure DevTest Labs', 'Service for quickly creating environments for testing.'),
            ('Azure API Management', 'Service for managing APIs in Azure.'),

            # Google Cloud Services - Compute
            ('Google Compute Engine', 'Scalable virtual machines on Google Cloud.'),
            ('Google App Engine', 'Platform as a service for building scalable web applications.'),
            ('Google Kubernetes Engine (GKE)', 'Managed Kubernetes service on Google Cloud.'),
            ('Google Cloud Functions', 'Serverless compute service for running event-driven functions.'),
            ('Google Cloud Run', 'Managed compute platform for running containers.'),
            ('Google App Engine Flexible Environment', 'Run custom runtimes on App Engine.'),
            ('Google Cloud Run for Anthos', 'Run containers on Kubernetes clusters managed by Anthos.'),
            ('Google Cloud VM Manager', 'Service for managing VM instances in a centralized way.'),
            ('Google Anthos', 'Platform for managing applications across on-premises and multiple clouds.'),
            ('Google Cloud Batch', 'Service for batch processing jobs on Google Cloud.'),

            # Google Cloud Services - Storage
            ('Google Cloud Storage', 'Unified object storage for data of any type.'),
            ('Google Cloud Filestore', 'Managed file storage service for applications.'),
            ('Google Cloud Bigtable', 'NoSQL database for big data analytics.'),
            ('Google Cloud Firestore', 'NoSQL document database built for global apps.'),
            ('Google Cloud Storage Nearline', 'Low-cost storage for data that is accessed infrequently.'),
            ('Google Cloud Storage Coldline', 'Low-cost storage for data that is rarely accessed.'),
            ('Google Cloud Storage Archive', 'Long-term storage for data that is rarely accessed.'),
            ('Google Cloud Backup and DR', 'Service for backing up and recovering data in Google Cloud.'),
            ('Google Persistent Disk', 'Block storage for Google Compute Engine.'),
            ('Google Transfer Appliance', 'Appliance for transferring large amounts of data to Google Cloud.'),

            # Google Cloud Services - Databases
            ('Google Cloud SQL', 'Managed relational database service for MySQL and PostgreSQL.'),
            ('Google Cloud Spanner', 'Globally distributed database service.'),
            ('Google Cloud Datastore', 'NoSQL database for web and mobile applications.'),
            ('Google Cloud Memorystore', 'Managed Redis and Memcached services.'),
            ('Google BigQuery', 'Serverless, highly scalable, and cost-effective data warehouse.'),
            ('Google Cloud Firestore', 'NoSQL document database for mobile, web, and server development.'),
            ('Google Cloud Dataproc', 'Managed Spark and Hadoop service for big data processing.'),
            ('Google Cloud BigQuery Omni', 'Multi-cloud analytics for BigQuery.'),
            ('Google Cloud Data Fusion', 'Data integration service for building ETL pipelines.'),
            ('Google Cloud BigQuery ML', 'Machine learning capabilities directly in BigQuery.'),

            # Google Cloud Services - Networking
            ('Google Cloud VPC', 'Virtual private cloud for isolating and connecting Google Cloud resources.'),
            ('Google Cloud Load Balancing', 'Distributes traffic across multiple backend instances.'),
            ('Google Cloud CDN', 'Content delivery network for delivering high-performance content globally.'),
            ('Google Cloud Interconnect', 'Service for connecting on-premises networks to Google Cloud.'),
            ('Google Cloud Router', 'Managed service for dynamic routing between Google Cloud and on-premises.'),
            ('Google Cloud Armor', 'Service for protecting applications from DDoS and other attacks.'),
            ('Google Cloud Network Intelligence Center', 'Service for monitoring network performance and health.'),
            ('Google Cloud Private Service Connect', 'Service for accessing Google services privately.'),
            ('Google Cloud DNS', 'Managed DNS service for Google Cloud resources.'),
            ('Google Traffic Director', 'Service for managing traffic to applications running on Kubernetes.'),

            # Google Cloud Services - Machine Learning & AI
            ('Google AI Platform', 'Unified platform for machine learning development.'),
            ('Google AutoML', 'Machine learning products that enable users to train high-quality models.'),
            ('Google Cloud Vision', 'API for image analysis.'),
            ('Google Cloud Speech-to-Text', 'API for converting audio to text.'),
            ('Google Cloud Text-to-Speech', 'API for generating spoken audio from text.'),
            ('Google Cloud Translation', 'API for translating text between languages.'),
            ('Google Cloud Natural Language', 'API for natural language understanding and analysis.'),
            ('Google Cloud Video Intelligence', 'API for analyzing video content.'),
            ('Google Cloud Dialogflow', 'Service for building conversational interfaces using natural language processing.'),
            ('Google Cloud AutoML Tables', 'Service for building and deploying ML models on structured data.'),

            # Google Cloud Services - Security
            ('Google Cloud Identity', 'Identity and access management for Google Cloud.'),
            ('Google Cloud Security Command Center', 'Unified security monitoring and risk management service for Google Cloud.'),
            ('Google Cloud Key Management Service', 'Service for managing cryptographic keys.'),
            ('Google Cloud Identity-Aware Proxy', 'Service for securing access to cloud applications.'),
            ('Google Cloud DLP', 'Service for discovering, classifying, and protecting sensitive information.'),
            ('Google Cloud Armor', 'Service for protecting applications from DDoS attacks.'),
            ('Google Cloud Security Scanner', 'Service for identifying vulnerabilities in applications.'),
            ('Google Cloud Security Health Analytics', 'Service for identifying security risks and compliance issues.'),
            ('Google Cloud Organization Policy', 'Service for managing resource configurations and policies.'),
            ('Google Cloud Chronicle', 'Service for security analytics and threat detection.'),

            # Google Cloud Services - Developer Tools
            ('Google Cloud Build', 'Continuous integration and delivery service.'),
            ('Google Cloud Source Repositories', 'Managed Git repositories for source control.'),
            ('Google Cloud Functions', 'Event-driven serverless computing platform.'),
            ('Google Cloud Deployment Manager', 'Infrastructure management tool for Google Cloud.'),
            ('Google Cloud Run', 'Managed service for running containerized applications.'),
            ('Google Stackdriver', 'Integrated monitoring and management service for applications.'),
            ('Google Cloud Monitoring', 'Service for monitoring applications and infrastructure.'),
            ('Google Cloud Logging', 'Service for centralized logging of application and system logs.'),
            ('Google Cloud Profiler', 'Service for analyzing the performance of applications.'),
            ('Google Cloud Trace', 'Service for analyzing and monitoring request latency in applications.'),

            # Miscellaneous Cloud Services
            ('Heroku Dynos', 'Scalable application containers on Heroku.'),
            ('DigitalOcean Droplets', 'Scalable virtual machines on DigitalOcean.'),
            ('Linode Compute', 'Scalable virtual machines on Linode.'),
            ('Vultr Cloud Compute', 'Scalable virtual machines on Vultr.'),
            ('Cloudflare Workers', 'Serverless computing platform on Cloudflare.'),
            ('Netlify Functions', 'Serverless compute service for deploying functions on Netlify.'),
            ('Fastly Compute@Edge', 'Serverless compute platform on Fastly.'),
            ('Oracle Cloud Infrastructure (OCI)', 'Comprehensive cloud services platform.'),
            ('Alibaba Cloud ECS', 'Elastic Compute Service for scalable cloud computing.'),
            ('IBM Cloud Foundry', 'Platform as a service for building and deploying applications.'),

            # Container Services
            ('Docker Hub', 'Container image repository.'),
            ('Kubernetes', 'Container orchestration platform.'),
            ('OpenShift', 'Container application platform.'),
            ('Amazon Elastic Kubernetes Service (EKS)', 'Managed Kubernetes service on AWS.'),
            ('Amazon Elastic Container Service (ECS)', 'Managed container service on AWS.'),
            ('Azure Kubernetes Service (AKS)', 'Managed Kubernetes service on Azure.'),
            ('Google Kubernetes Engine (GKE)', 'Managed Kubernetes service on Google Cloud.'),
            ('Red Hat OpenShift', 'Enterprise Kubernetes platform.'),
            ('Rancher', 'Open-source container management platform.'),
            ('Helm', 'Package manager for Kubernetes.'),

            # Backup and Recovery
            ('AWS Backup', 'Service for centralized backup management across AWS services.'),
            ('Azure Backup', 'Service for backing up data in Azure.'),
            ('Google Cloud Backup and DR', 'Service for backing up and recovering data in Google Cloud.'),
            ('Veeam Backup', 'Backup and recovery solution for cloud data.'),
            ('Acronis Cyber Backup', 'Backup and recovery service with ransomware protection.'),
            ('Commvault Complete Backup & Recovery', 'Unified data protection solution.'),
            ('IBM Cloud Backup', 'Backup as a service for cloud data.'),
            ('Druva Cloud Platform', 'Cloud-based data protection and management.'),
            ('Carbonite Cloud Backup', 'Service for backing up data to the cloud.'),
            ('Zerto IT Resilience Platform', 'Disaster recovery and backup solution.'),
        ]

        for asset_name, asset_description in assets:
            Asset.objects.update_or_create(
                name=asset_name,
                defaults={'description': asset_description}
            )

        self.stdout.write(self.style.SUCCESS(f'Successfully seeded {len(assets)} assets!'))
