from django.core.management.base import BaseCommand
from assets_management.models import Asset

class Command(BaseCommand):
    def handle(self, *args, **options):
        assets = [
            ('Servers', 'High-performance computers designed to manage network resources and host applications.'),
            ('Laptops', 'Portable computers used by employees for various tasks.'),
            ('Desktops', 'Stationary computers typically used in office settings.'),
            ('Network Equipment', 'Devices like routers, switches, and modems used to connect and manage network traffic.'),
            ('Storage Devices', 'Devices such as hard drives and SSDs used to store data.'),
            ('Printers', 'Devices used to produce physical copies of digital documents.'),
            ('Scanners', 'Devices used to digitize physical documents and images.'),
            ('ERP Systems', 'Integrated software platforms used for managing core business processes.'),
            ('CRM Systems', 'Software used to manage customer relationships and sales activities.'),
            ('Financial Management Software', 'Applications used to manage financial transactions and reporting.'),
            ('Operating Systems', 'Software that manages computer hardware and software resources.'),
            ('Development Tools', 'Software tools used for writing and testing code, such as IDEs and version control systems.'),
            ('Customer Data', 'Information about customers, including contact details and purchase history.'),
            ('Financial Records', 'Documents and files containing financial transactions and statements.'),
            ('Employee Records', 'Files and data related to employee information and HR activities.'),
            ('Security Logs', 'Records of security-related events and activities within an IT system.'),
            ('Research Data', 'Information collected during research activities, often used for analysis and reporting.'),
            ('Sales Data', 'Information about sales transactions, customer purchases, and sales performance.'),
            ('Office Buildings', 'Physical structures used as workplaces for employees.'),
            ('Data Centers', 'Facilities used to house computer systems and associated components.'),
            ('Manufacturing Equipment', 'Machines and tools used in the production of goods.'),
            ('Vehicles', 'Transportation assets such as company cars, delivery trucks, and vans.'),
            ('Power Generators', 'Equipment used to provide backup or primary power supply.'),
            ('Cooling Systems', 'Systems used to regulate temperature in data centers and other critical environments.'),
            ('Website Content', 'Digital material published on a company\'s website, including text, images, and multimedia.'),
            ('Social Media Accounts', 'Platforms used to engage with customers and promote brand presence.'),
            ('Blogs', 'Online journals or informational sites managed by the organization.'),
            ('E-books', 'Digital books used for training, marketing, or informational purposes.'),
            ('Multimedia Assets', 'Digital content such as videos and images used for marketing or internal communications.'),
            ('Patents', 'Legal rights granted for inventions and innovations.'),
            ('Trademarks', 'Symbols, logos, or names legally registered or established for a company’s products or services.'),
            ('Trade Secrets', 'Confidential business information that provides a competitive edge.'),
            ('Copyrights', 'Legal rights granted to creators of original works of authorship.'),
            ('Proprietary Algorithms', 'Unique algorithms developed and owned by the organization for specific applications.'),
            ('Business Continuity Plans', 'Strategies and procedures for maintaining operations during disruptions.'),
            ('Compliance Procedures', 'Processes to ensure adherence to regulatory requirements and standards.'),
            ('Operational Workflows', 'Established sequences of tasks and activities used in daily operations.'),
            ('Quality Assurance Processes', 'Procedures and standards to ensure product or service quality.'),
            ('Vendor Contracts', 'Agreements with suppliers or service providers for goods or services.'),
            ('Service Agreements', 'Contracts defining the terms of service provided by external parties.'),
            ('Licensing Agreements', 'Contracts granting rights to use or distribute intellectual property.'),
            ('Non-Disclosure Agreements', 'Contracts to protect confidential information shared between parties.'),
            ('Heavy Machinery', 'Large machines used in construction or industrial operations.'),
            ('CNC Machines', 'Computer-controlled tools used for precision machining.'),
            ('Printing Presses', 'Machines used for producing printed materials in bulk.'),
            ('Company Cars', 'Vehicles owned by the company for employee use and business purposes.'),
            ('Delivery Trucks', 'Vehicles used for transporting goods to customers or other locations.'),
            ('Forklifts', 'Vehicles used for lifting and moving materials in warehouses or manufacturing areas.'),
            ('Company Vans', 'Vehicles used for various business-related activities, such as transportation and deliveries.'),
            ('Project Documentation', 'Files and records related to specific projects, including plans and progress reports.'),
            ('Compliance Documentation', 'Records proving adherence to regulatory requirements and standards.'),
            ('Manuals', 'Documents providing detailed instructions on operating equipment or systems.'),
            ('Policy Documents', 'Written guidelines and rules governing organizational behavior and operations.'),
            ('Technical Specifications', 'Detailed descriptions of technical requirements and standards for products or systems.'),
            ('Telephony Systems', 'Communication systems used for voice calls, including traditional phones and VoIP systems.'),
            ('Video Conferencing Tools', 'Software and hardware used for virtual meetings and collaboration.'),
            ('Email Systems', 'Platforms used for electronic mail communication.'),
            ('Instant Messaging Platforms', 'Software for real-time text-based communication between users.'),
            ('Routers', 'Devices that direct data traffic between networks.'),
            ('Switches', 'Network devices that manage data traffic within a network.'),
            ('Firewalls', 'Security devices or software that monitor and control network traffic based on predetermined rules.'),
            ('Network Cables', 'Wires used to connect network devices and transmit data.'),
            ('Network Hubs', 'Devices that connect multiple network devices and distribute data to all of them.'),
            ('Surveillance Cameras', 'Cameras used to monitor and record activities for security purposes.'),
            ('Alarm Systems', 'Devices that alert to potential security breaches or other emergencies.'),
            ('Access Control Systems', 'Systems that manage and restrict access to physical or digital spaces.'),
            ('Intrusion Detection Systems', 'Systems that monitor for and respond to unauthorized access attempts.'),
            ('Cloud Storage Solutions', 'Services that provide scalable storage over the internet.'),
            ('Cloud Computing Platforms', 'Services that offer computing power, storage, and other resources via the cloud.'),
            ('SaaS Applications', 'Software applications hosted by a provider and accessed via the internet.'),
            ('Training Manuals', 'Documents used to guide training sessions and provide instruction.'),
            ('E-learning Modules', 'Online courses and training materials delivered via the internet.'),
            ('Workshops', 'Interactive training sessions designed to develop skills and knowledge.'),
            ('Certification Programs', 'Training and assessment programs that provide professional certifications.'),
            ('CRM Interfaces', 'User interfaces for managing customer relationships and interactions.'),
            ('Customer Support Portals', 'Online platforms for customers to seek help and support services.'),
            ('Online Customer Service Platforms', 'Web-based tools for customer service, including chat and ticketing systems.'),
            ('Prototype Models', 'Early versions of products used for testing and feedback.'),
            ('Experimental Data', 'Data collected from experimental activities or research.'),
            ('Research Reports', 'Documents detailing research findings and conclusions.'),
            ('Innovation Labs', 'Facilities dedicated to developing and testing new ideas and technologies.'),
            ('Investment Portfolios', 'Collections of financial assets held for investment purposes.'),
            ('Securities', 'Financial instruments that represent ownership or debt, such as stocks and bonds.'),
            ('Bonds', 'Debt securities issued by entities to raise funds, paying interest to investors.'),
            ('Insurance Policies', 'Contracts providing financial protection against various risks.'),
            ('Legal Cases', 'Records and documents related to legal disputes and proceedings.'),
            ('Court Judgments', 'Official decisions issued by courts in legal cases.'),
            ('Legal Filings', 'Documents submitted to courts or other legal entities.'),
            ('Intellectual Property Registrations', 'Official records of intellectual property rights, such as patents and trademarks.'),
            ('Environmental Compliance Documents', 'Records demonstrating adherence to environmental regulations and standards.'),
            ('Sustainability Reports', 'Documents outlining environmental impact and sustainability efforts.'),
        ]

        for name, description in assets:
            Asset.objects.get_or_create(name=name, defaults={'description': description})

        self.stdout.write(self.style.SUCCESS('Successfully seeded the Asset model.'))
